version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/code-camp-team-project-350914/team-project:0.1
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
